### ISSUE TITLE
[Linux] Wrong binary path for yuzu

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [CapitaineJSparrow/emusak-ui#108] opened 2021-07-31 19:13 UTC
Good afternoon. 
I ran into a problem, in Archlinux, the path to the folder with Yuzu files is~/. local/share/yuzu/ 
But Emusak uses a different one by default and does not want to change it in any way. Is there a way to specify the desired path to the program, as it is implemented for Reyujinx?

**Comment by CapitaineJSparrow** [comment] 2021-07-31 19:33
Hey @Vochatrak-az-ezm Thanks for reporting ! It's definitely an issue for linux users and I'm sad to tell you there is no way to change the yuzu path on linux as described on changelog ([V1.0.87](https://github.com/CapitaineJSparrow/emusak-ui/releases/tag/v1.0.87)). 

I'll provide a patch soon for linux users since this issue is major. Can you please specify 

* How did you installed yuzu ? 
* What is your OS and package manager used if you installed yuzu with. 
* Additionaly, can you tell me where is located shaders and mods ? You can find it by clicking right click on any game in yuzu then open shader cache or open mods folder

Also please note i'm actively working on yuzu portable installaton

Thanks !

**Comment by Vochatrak-az-ezm** [comment] 2021-07-31 19:48
Installed Yuzu from the archlinuxcn repository.  I installed it as a full-time pacman package manager.
OS - Arco Linux (this is Arch linux with a graphical installer)
Shaders - /home/**USER**/.local/share/yuzu/shader/0100FF500E34A000/   (The numbers at the end are the ID of a specific game)
Mods - /home/**USER**/.local/share/yuzu/load/0100FF500E34A000/  (The numbers at the end are the ID of a specific game)
*Instead of the word "**USER**" the user name

**Comment by CapitaineJSparrow** [comment] 2021-07-31 19:50
Thanks for detailled report. I think this issue is the same as https://github.com/CapitaineJSparrow/emusak-ui/issues/101 but for yuzu. Can you tell me if `yuzu` command is in path ? (or any command to launch yuzu)

**Comment by Vochatrak-az-ezm** [comment] 2021-07-31 20:36
I'm sorry, but I don't understand the question. If we are talking about the $PATH variable, then yuzu is not registered there. If it meant the way to yuzu itself then /usr/sbin/yuzu

**Comment by CapitaineJSparrow** [comment] 2021-07-31 20:38
![image](https://user-images.githubusercontent.com/6690149/127751927-d7d08444-15b8-4833-943d-dcf3f2132eca.png)

Thanks again for reporting, should be fixed by latest emusak release (1.0.90). Let me know if it is working ! Please note yuzu portable is not yet supported (where you create a "user" folder to avoid yuzu to writes files in `$HOME/.local/share`)

Let me know if your problem is solved

**Comment by Vochatrak-az-ezm** [comment] 2021-07-31 21:17
It downloads the keys correctly, but does not see the game. Accordingly, there is no way to download mods or saves.

**Comment by CapitaineJSparrow** [comment] 2021-07-31 21:19
@Vochatrak-az-ezm I can confirm games are shown correctly, but you have to run any game in yuzu first (to load cache which is read by emusak) then use the reload button near "filter games" input or relaunch emusak again

**Comment by Vochatrak-az-ezm** [comment] 2021-07-31 21:25
No and after starting the game, and after reload and even after force reload shows 0 games (ryujinx works fine).

**Comment by CapitaineJSparrow** [comment] 2021-07-31 21:48
@Vochatrak-az-ezm 

Can you this dev build and let me know if issue is solved ? Yuzu seems to manage cache differently from windows. 

[RPM](https://e.pcloud.link/publink/show?code=XZVDf0ZQId4jIfyRNhrVAqJbrxTpkrCmtwV)
[AppImage](https://e.pcloud.link/publink/show?code=XZJDf0Zs5ak4IkzpoSGaEJYfhWov8NaTlTX)
[deb](https://e.pcloud.link/publink/show?code=XZpDf0ZBIpuM07yozJKIdFghWNLwzSPQPA7]

![image](https://user-images.githubusercontent.com/6690149/127753138-ecd84ff3-7e8a-45ca-86ef-5e01a8d6fe74.png)

**Comment by Vochatrak-az-ezm** [comment] 2021-07-31 22:01
Yes, it works now.

**Comment by CapitaineJSparrow** [comment] 2021-07-31 22:10
Thanks for everything @Vochatrak-az-ezm !

**Closed** 2021-07-31 22:10 UTC
Labels: Linux, yuzu
